### ISSUE TITLE
Error when using a string as a tooltip template

### ISSUE THREAD

**Issue by WeKyle** [720kb/angular-tooltips#134] opened 2015-12-15 22:57 UTC
I'm on `1.0.6` after migrating from `0.1.25`.

I dropped in `tooltip-template` in the place of `tooltip-title`, and now I'm getting an error every time a tooltip appears.

For example, this tooltip:

```
<li class="back"><a class="icon icon-angle-left" href="#" ng-click="cdvm.goBack()" tooltips tooltip-template="Go back"></a></li>
```

throws this error:
```
Uncaught Error: [$parse:syntax] Syntax Error: Token 'back' is an unexpected token at column 4 of the expression [Go back] starting at [back].
http://errors.angularjs.org/1.4.8/$parse/syntax?p0=back&p1=is%20an%20unexpected%20token&p2=4&p3=Go%20back&p4=back
```

The tooltip shows up normally, however. 

I think I'm using `tooltip-template` correctly, since the docs say I can just use text. I tried wrapping the text in single quotes since Angular was picking them up as tokens, and the tooltip began to be placed strangely on the page. In addition, the single quotes were visible, so that's obviously not what's intended.

**Comment by wouldgo** [comment] 2015-12-17 23:25
Hi,

this is quite strange since, for instance, [here](https://github.com/720kb/angular-tooltips/blob/master/index.html#L95) we have a variety of templates with simple strings...

As soon as I can I'll take a look, or If you want to investigate a little more we really appreciate.

**Comment by alexey** [comment] 2015-12-19 10:54
I have similar error when `tooltip-template=""` has space.
Also i have js warning `$tooltip is now deprecated. Use $uibTooltip instead.` somewhere is angular.js
angular 1.4.0

@WeKyle do you have ui-bootstrap-tpls.js in your project ? 
Im my trace i have reference to this line:
`bower_components/angular-bootstrap/ui-bootstrap-tpls.js:5023:56`

Which is related to $tooltip service, i bet the problem is out there. Will check later when i get back to computer.

**Comment by alexey** [comment] 2015-12-19 13:44
@WeKyle 
In my case, yes it is the problem, its conflicts with angular ui bootstrap(which already has tooltip support)
See tooltip section of http://angular-ui.github.io/bootstrap/
Ill have to continue with ui bootstrap since i use alot from it.

**Comment by WeKyle** [comment] 2015-12-21 22:37
@alexey good catch. It's not in use, but we do have `angular-bootstrap` in our project, too.

@wouldgo the best way to address this would be to have the option to namespace the `angular-tooltips` directive.

**Comment by wouldgo** [comment] 2015-12-30 18:22
Hi again (I was in vacation :smile:),

there already is a discussion about the namespacing in #129 the main fact points are explained in my first comment.

Closing this.

**Closed by wouldgo** 2015-12-30 18:22 UTC

**Comment by Chima1707** [comment] 2016-04-15 08:44
@wekyle Did you succeed in name spacing angular-bootstrap?
