### ISSUE TITLE
Tooltip does not show at the 'bottom' if text is more than 24 odd chars.

### ISSUE THREAD

**Issue by rupakg** [720kb/angular-tooltips#27] opened 2015-04-16 17:57 UTC
This works:
```<div class="info" tooltips tooltip-side="bottom" tooltip-size="large" tooltip-content="this is a very long text"></div>```

![image](https://cloud.githubusercontent.com/assets/8188/7187640/fa402450-e43f-11e4-85da-6d6795b17308.png)

But this does not:
```<div class="info" tooltips tooltip-side="bottom" tooltip-size="large" tooltip-content="this is a very long text another word"></div>```

![image](https://cloud.githubusercontent.com/assets/8188/7187655/1b1c4c12-e440-11e4-82d4-e5b2b1a8ca27.png)

**Comment by 45kb** [comment] 2015-04-17 10:45
Hi @rupakg  thank for reporting, could you provide a plunkr or jsfiddle including your full css code so that we are all able to investigate?

Thank you

**Comment by rupakg** [comment] 2015-04-20 15:06
Hi @45kb, thanks for your suggestion. I tried using 

``` tooltip-try="false" ```

and it started showing the tooltip at the bottom.

![image](https://cloud.githubusercontent.com/assets/8188/7233063/09cc32e6-e74d-11e4-8e18-c3c407f0b1fb.png)

But I noted while testing that if the tooltip is on the left edge of the screen, the tooltip is chopped off from the left side.

Thanks again, I appreciate your help.

**Comment by 45kb** [comment] 2015-04-20 15:25
Hi, yes actually there are bugs on positioning we are trying to solve everything.
@KynoYang do you think this is another bug caused by what we talked about yesterday?

**Comment by rupakg** [comment] 2015-04-20 21:00
@45kb Thanks all for looking at this.

**Comment by KynoYang** [comment] 2015-04-21 06:17
@45kb I've found the cause of this problem. Check your hangout :laughing:

**Comment by 45kb** [comment] 2015-04-21 07:49
Hi guys, thanks @KynoYang  for the PR, now @rupakg  try with these changes https://github.com/720kb/angular-tooltips/pull/28

And if it does not work yet, please paste all your css and html so we check better, but this Pr should fix the positioning problem

Also, you can now remove tooltip-try="false"

Let know please. thank you a lot.

**Comment by rupakg** [comment] 2015-04-22 00:59
Thanks all for working this. I will test tomm. and let you guys know.

**Comment by 45kb** [comment] 2015-07-21 08:39
@rupakg  any news? i am going to close the issue, feel free to re-open this if you need.
thanks

**Closed by 45kb** 2015-07-21 08:39 UTC
Labels: bug, enhancement
