### ISSUE TITLE
Tooltips lose position in scrollable elements

### ISSUE THREAD

**Issue by ac360** [720kb/angular-tooltips#25] opened 2015-04-07 07:53 UTC
First off, I love this library.  It's really wonderful. 

I'm running into an issue where I have tooltips on elements inside of a scrollable area.  The scrollable area is using a javascript scrolling solution (perfect scroll bar).  Unfortunately, the tooltips lose their position upon scrolling. 

Is there a way to re-initialize them on a scroll event?  Perhaps a CSS fix?

Thanks for the wonderful library :)

**Comment by wouldgo** [comment] 2015-04-07 08:13
Hi @ac360,

first of all thanks for using this tooltip directive! As a starting point, we appreciate a lot a snippet in plunkr (or other service like that) where we can review the issue. We discuss rigth now that we have many use cases uncovered by our (manual) tests, so with your reported issue we can start to build up some e2e test.

**Comment by jclarke0000** [comment] 2015-04-08 18:23
I really like this module, but I am running in to this issue as well.  I couldn't make plunkr work, so I'll do my best to describe how to reproduce this issue:

Create a scrollable element (e.g.: div with overflow:auto), and give it a fixed height.  Fill it with enough content such that the container scrolls.  Put an element with the tooltips directive anywhere in this scrolling container.  Now with this rendered in the browser, scroll the element until the element with the tooltip directive is visible.  Hover the element, and you will see the tooltip render well below where it should.

It looks like the positioning does not factor in the scrollTop of the parent element.

I hope this helps!
 - Jeff

**Comment by 45kb** [comment] 2015-04-15 14:39
Hi, so now the bug it's clear thanks a lot.

We should consider that the directive should recognize if the element is moving (scrolling) in the page, because simply Re-Positioning the tooltip on Window Scroll would not be enough....

If you guys have some time and would try something for this we'll be much glad, seriously @jclarke0000  @ac360

**Comment by omarjcamo** [comment] 2015-05-11 15:45
Hello there! Thanks for the library as well, great stuff!

Just to add a note on this one.. In my case it's not related with a scrollable container but with a series of elements generated by an ng-repeat. Each of these elements has a tooltip. I add and remove dynamically these elements and in this process, the position of the tooltips get messed up.

In other words, imagine a repeater of inline boxes with different widths and a tooltip each, such as: 

[A] [B] [C] [D] [E]

If I remove dynamically, say [C] and I get [A] [B] [D] [E], D's tooltip would be still around the top of [E], instead of re-positioning as well to the left.

I hope this helps, I'll see if I can get a plunkr working with this.

**Comment by noahbornstein** [comment] 2015-05-27 07:02
I had the same issue and fixed the problem by editing the following functions to retrieve offsets *relative to the viewport*, rather than parent containers. (This started around line 100 in unminified script):
```
        $scope.getRootOffsetTop = function getRootOffsetTop (elem){
          return elem.getBoundingClientRect().top;
        };

        $scope.getRootOffsetLeft = function getRootOffsetLeft (elem){
          return elem.getBoundingClientRect().left;
        };
```
`getBoundingClientRect()` returns an object with coordinates (top, bottom, left, and right) relative to the viewport. So long as this calculates each time at the trigger, it should work!

**Comment by 45kb** [comment] 2015-05-27 07:07
@noahbornstein Hi, thank you for the tip, does it fixed the problem at all? 
Could you PR it so we can merge? :+1:

**Comment by fronterweb** [comment] 2015-06-14 19:04
@noahbornstein 
works but not in my case.

I have scrollable list. Each item of this list has tooltip.
Tooltip breaks when you scroll page and scrollable list. 

IMO best option would if I be able to set parent element of tooltip.
Now all tooltips lands right before end of <body> tag. It's bad for me.

**Comment by amichard** [comment] 2015-06-17 21:19
Hi.

Thanks for the suggested fix using getBoundingClientRect(). I found that I had to subtract scrollTop and scrollLeft to make it work for me.

```javascript
         $scope.getRootOffsetTop = function getRootOffsetTop (elem, val){
          if (elem.offsetParent === null){

            return val + elem.offsetTop;
          }

          return $scope.getRootOffsetTop(elem.offsetParent, val + elem.offsetTop - elem.scrollTop);
        };

        $scope.getRootOffsetLeft = function getRootOffsetLeft (elem, val){

          if (elem.offsetParent === null){

            return val + elem.offsetLeft;
          }

          return $scope.getRootOffsetLeft(elem.offsetParent, val + elem.offsetLeft - elem.scrollLeft);
        };
```

I hope this helps.

**Comment by 45kb** [comment] 2015-06-18 06:50
@amichard  this is a good solution, maybe the best one! Can't you PR it if everything working correctly?

thank you

**Comment by amichard** [comment] 2015-06-18 15:53
Hi.

Thanks! I'll do a bit more testing and try to put a request in later.

**Comment by Joao-Martins** [comment] 2015-06-22 15:04
Hey, first of all, thanks for this lib. It's great. Although, I'm running into this issue too. Inside an <ul> with a fixed height and overflow-y: auto; the items below the defined height have the tool-tip badly positioned once you scroll through the list.

Has this issue been fixed yet?

**Comment by 45kb** [comment] 2015-06-23 08:43
@Joao-Martins  hi, you can try now that we merged he @amichard  PR(https://github.com/amichard/angular-tooltips/commit/f315f66e923ab81e26e572c25733a0799658552e) let know please if you try.

**Comment by Joao-Martins** [comment] 2015-06-23 09:35
Hello @45kb I updated the lib with bower and the issue seems to be occurr and I get the same wrong behavior of the tooltips. Below it's a print screen of what is happening. Thanks.
http://i.imgur.com/m7FOH5X.png

**Comment by 45kb** [comment] 2015-06-23 09:37
@Joao-Martins  it is not yet updated on bower, try manually including this file https://github.com/720kb/angular-tooltips/blob/master/src/js/angular-tooltips.js :+1:

**Comment by ksr583** [comment] 2015-06-23 20:39
I was having this same issue, and the replacement of the file suggested above fixed it for me. Thanks!

**Comment by 45kb** [comment] 2015-06-24 07:24
Hi, so now the change is live togheter with the new attribute (tooltip-html="") , you can update your module version to the latest if you need (https://github.com/720kb/angular-tooltips/releases/tag/0.1.13)

Thank you all for the support i am going to close the issue.

If problem persists please feel free to open this issue again.

**Closed by 45kb** 2015-06-24 07:24 UTC
Labels: bug, enhancement
