### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by adarshk111** [720kb/angular-tooltips#70] opened 2015-07-24 08:09 UTC
Is there no work around to make it work in IE at all? Not even in IE11?
I did not realize there was a question mark on IE support, and its a little too late for me to go back:(

**Comment by adarshk111** [comment] 2015-07-24 08:21
<a href="#" class="useBootstrap col-sm-2" tooltips tooltip-side="right" tooltip-html="{{ row.FileName }} <br> {{ row.DocumentUploadedBy }} " tooltip-show-trigger="mouseover click">
                                        {{ row.FileName | limitTo: 15 }}{{row.FileName.length > 15 ? '...' : ''}}
                                    </a>
This is what I am using

**Comment by 45kb** [comment] 2015-07-24 08:29
Hi @adarshk111 , yes everything is possible, unless it's an AngularJS core problem.
Let know if you try anything for this and what the problem is.
Feel free to PR at anytime, thank you :+1:

**Comment by adarshk111** [comment] 2015-07-24 08:57
Hi sure. Although i did go through the list of issues and I saw IE issue is fixed, I am using  
tooltips tooltip-side="right" tooltip-html ,tooltip-show-trigger="mouseover click" . Just wanted to know if anything I am using it wrongly?

**Comment by 45kb** [comment] 2015-07-24 09:08
Everything looks ok, what warning/error do you get in console? 
What's happening on the page, anything strange?

Please try to debug a little bit and report some specific problem so we may help you :+1:

**Comment by adarshk111** [comment] 2015-07-24 09:32
Unfortunately do not see any error in the console. When I click/ hover nothing happens. Works perfectly fine in chrome:(

**Comment by adarshk111** [comment] 2015-07-24 09:33
I changed tooltip-html to normal tooltip-content suspecting if rendering html was the problem, but no change..

**Comment by 45kb** [comment] 2015-07-24 09:35
@adarshk111 Can you run the repo index.html on your browser and see if that works?

Just:

```git clone  https://github.com/720kb/angular-tooltips tooltips && cd tooltips && npm install && grunt```

Then go to ```localhost:8000```

You should see the testing page

**Comment by adarshk111** [comment] 2015-07-24 09:41
Syntax Error: Token 'Name' is an unexpected token at column 10 of the expression - I see this error in Chrome infact, I use Angular with MVC in Visual Studio, not very familiar with npm install and grunt

**Comment by 45kb** [comment] 2015-07-24 09:42
Also not very familiar with console debug ;P you should be able to debug a little bit and report specific problems, anyway give us some time we will try something as soon as possible

**Comment by 45kb** [comment] 2015-07-24 09:48
@adarshk111  one last thing, could you please post your code in a jsfiddle or plunkr, because i need to check what's happening, the TOKEN Name error, looks like something wrong in your code and not in the directive

**Comment by adarshk111** [comment] 2015-07-24 09:49
The error I pasted above is due to some dynamic content {{ }} inside tooltip-html, but even when i replaced it with static content, it did not work in IE11

**Comment by 45kb** [comment] 2015-07-24 09:51
@adarshk111  Please post the code, i can't help you without looking at the code :8ball:

**Comment by adarshk111** [comment] 2015-07-24 10:01
wip - http://jsfiddle.net/pncfLdd4/1/         yet to mock service calls

**Comment by adarshk111** [comment] 2015-07-24 10:16
http://jsfiddle.net/pncfLdd4/9/ - still couldnt get angular running though. ive included Angular 1,2

**Comment by Script-Shiva** [comment] 2015-07-24 10:24
I am too facing the same issue. I found that tooltip position is getting set to left:-200% and it is not getting adjusted to hover element position.

**Comment by adarshk111** [comment] 2015-07-24 10:33
http://jsfiddle.net/AKAKAK4/0wnth09j/2/ - this is the basic thing I am trying to do

**Comment by Script-Shiva** [comment] 2015-07-24 10:40
@45kb I just confirmed that positions are not getting updated in the tooltip div style tag. In your page it is updated to element position, but in our page it is stuck at left: -200% and not updating.

**Comment by adarshk111** [comment] 2015-07-24 10:43
@Script-Shiva  How did u check it in the browser?

**Comment by 45kb** [comment] 2015-07-24 10:44
Does this works for you http://jsfiddle.net/u898mg2m/1/

PS: please post working examples or we can't help you much

**Comment by 45kb** [comment] 2015-07-24 10:45
sorry http://jsfiddle.net/u898mg2m/2/ updated

**Comment by 45kb** [comment] 2015-07-24 10:46
@Script-Shiva  browser version?

**Comment by adarshk111** [comment] 2015-07-24 10:48
Not in IE , works in chrome. IE11 is what i have

**Comment by Script-Shiva** [comment] 2015-07-24 10:50
Working perfectly in other browsers. But in IE tooltip is not shown. See the position left:-200%. It always is placed out of window. Not getting updated.

![error pos](https://cloud.githubusercontent.com/assets/4113772/8872999/cd04c224-321f-11e5-80d5-d4a8901c5142.png)

**Comment by Script-Shiva** [comment] 2015-07-24 10:51
@45kb Am using IE11, demo page is working perfectly in IE. But your fiddle and my implementation are not.

**Comment by 45kb** [comment] 2015-07-24 10:52
Yes maybe is that!
i will try to check what's happening and ask you to try again let's see if we can fix it.

What about IE9 and IE10, do you even know?

**Comment by Script-Shiva** [comment] 2015-07-24 10:52
Let me check and reply back.

**Comment by 45kb** [comment] 2015-07-24 10:53
@Script-Shiva ok thanks please let know we need to clarify this. :+1:

**Comment by Script-Shiva** [comment] 2015-07-24 10:57
@45kb IE10 - Demo page is working but fiddle is not.

**Comment by 45kb** [comment] 2015-07-24 10:58
IE11 - demo page is working for you?

**Comment by Script-Shiva** [comment] 2015-07-24 11:00
Yes working in both IE10 and IE11. But fiddle is not working.

IE8 - Nothing works ;)

**Comment by Script-Shiva** [comment] 2015-07-24 11:01
Can you see if you are facing any NaN issue while calculating px in IE. I usually face this while setting styles in IE, other browsers take numbers but IE needs number+'px' to work.

**Comment by 45kb** [comment] 2015-07-24 11:05
so IE 8 is deprecated by Angular latest versions, IE10 and IE11 working fine by the example page, what's the problem now? :)

**Comment by 45kb** [comment] 2015-07-24 11:06
I will make a commit and see if it's still working on IE11 and IE10 (the example page)

**Comment by 45kb** [comment] 2015-07-24 11:08
@Script-Shiva  please if you can, git pull the repo and try again the example page on IE10 and IE11, i updated the angular version maybe with latest version there are problems...

Let me know if you can, thank you a lot

**Comment by Script-Shiva** [comment] 2015-07-24 11:19
@45kb I will pull the repo and see if I could fix. Thanks for your time. Ping me if you find any fix.

**Comment by 45kb** [comment] 2015-07-24 13:00
@Script-Shiva  Hi, can you try replacing this class in the tooltip.css file ?

this
```._720kb-tooltip {
  background: rgba(0, 0, 0, 0.8);
  color:white;
  position:absolute;
  z-index:9;
  padding:0.4% 1%;
  opacity:0;
  visibility: hidden;
  -webkit-border-radius:3px;
  -moz-border-radius:3px;
  border-radius:3px;
  top: 0;
left:-200%;
}```

to this

```._720kb-tooltip {
  background: rgba(0, 0, 0, 0.8);
  color:white;
  position:absolute;
  z-index:9;
  padding:0.4% 1%;
  opacity:0;
  visibility: hidden;
  -webkit-border-radius:3px;
  -moz-border-radius:3px;
  border-radius:3px;
  top: 0;
}```

**Comment by Script-Shiva** [comment] 2015-07-24 14:03
@45kb Now I am able to see the tooltip at (0,0) position of the window. But the position is not updating to the tooltip element location.

**Comment by Script-Shiva** [comment] 2015-07-24 14:23
I have fixed the issue. I think this repo is not updated. In the demo the version of the files are v1.6, but in the repo they are still v1.16

@45kb Please update the repo so I could do a bower update. Ping me once done.

@adarshk111 Try to download the js and css files from their [demo link and use in project. It is working perfectly in IE.

DEMO - http://720kb.github.io/angular-tooltips/

Thanks for your support @45kb You could close the issue once updating the repo. ;)

**Comment by 45kb** [comment] 2015-07-24 14:32
Ok guys, could you please try to use these files https://github.com/720kb/angular-tooltips/tree/master/src

I think we fixed the problems on IE11 at least, let know please.

:+1:

**Comment by 45kb** [comment] 2015-07-24 14:34
Problem fixed by @Ryppy :100:

**Comment by Script-Shiva** [comment] 2015-07-24 15:08
@45kb It is working fine. Could you release a new version so that I can perform a bower update.

**Comment by 45kb** [comment] 2015-07-24 15:08
@Script-Shiva  Yes going to! Thank you for feedbacks.

**Comment by 45kb** [comment] 2015-07-24 15:13
shipped https://github.com/720kb/angular-tooltips/releases/tag/0.1.17

**Closed by 45kb** 2015-07-24 15:13 UTC
Labels: help wanted, question

**Comment by adarshk111** [comment] 2015-07-27 13:13
Thanks a lot both @45kb and @Script-Shiva ! . it works perfectly. Thank you for making my life easy! Sorry for the delayed response, i integrated this fix only today.

**Comment by 45kb** [comment] 2015-07-27 13:15
Glad if it works @adarshk111  thanks goes all to @Ryppy  :+1:

**Comment by Thomaspunt** [comment] 2015-08-03 12:38
Thanks for the update, works splendid! 
I noticed in IE10 that `_720kb-tooltip` class displays a small box which overlays the button on which the tooltip is applied. I've added a `pointer-events: none` to the `_720kb-tooltip` class to solve this.

**Comment by 45kb** [comment] 2015-08-03 12:41
@Thomaspunt  do you have any screen of that ? Glad if you enjoying it :)

**Comment by Thomaspunt** [comment] 2015-08-03 13:13
![720kb-tooltips-ie11 0 21](https://cloud.githubusercontent.com/assets/2996457/9038116/16f5eba4-39f2-11e5-9bb2-7a0d676f7b38.JPG)

There you go.

**Comment by 45kb** [comment] 2015-08-03 13:15
@Thomaspunt  awesome, could you please  PR it?
